### ISSUE TITLE
Allow non authenticated users

### ISSUE THREAD

**Issue by nextgen-networks** [juliushaertl/apporder#24]
AppOrder 0.3.2 & 0.3.3 forces constantly reloading the website if user is not authenticated/anonymous.

This is an rare situation but can be easily rebuild when using the polls app and creating an public link to an poll.

More Info?
Please check the original bug-report that was created for the polls app:
https://github.com/v1r0x/polls/issues/96#issuecomment-258151458

![image](https://cloud.githubusercontent.com/assets/21206978/19969580/736186d2-a1d9-11e6-99ca-597c60bbdda2.png)

**Comment by juliushaertl** [comment]
@nextgen-networks Thanks for your report. In my point of view this is something that needs to be fixed in the polls repo, as this is not happening on other public pages (e.g. public file shares)

I just had a quick look, but it looks like the TemplateResponse constructor in your controller needs an additional parameter ($renderAs='guest') for public pages. I'm sorry I cannot test that right now, but I'll do so if i find some time.

**Comment by nextgen-networks** [comment]
@juliushaertl Thanks for your feedback. I'll close this thread an had reopened the polls thread already.
